[project]
name = "mlx-whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ffmpeg>=1.4",
    "ipykernel>=6.29.5",
    "openai-whisper>=20250625",
    "torch>=2.7.1",
]
